export default {
    User: [],
    AllCommittee: [],
    AllExpert: [],
    WonderfulPictures: [],
    MediaVideo: [],
    Meeting: [],
    DrawRecord: [],
    SingleMeeting: [],
    News: [],
    MeetingDetail: [],
    NewsDetail: [],
    SingleNews: [],
    Activity: [],
    SingleActivity: [],
    IntegralDetail: [],
    IntegralGifts: [],
    Blog: [],
    Question: [],
    SingleQuestion: [],
    ActivityAndMeetingChoice: [],
    ThumbBlogShare: [],
}