export default {
    User: [],
    AllCommittee: [],
    AllExpert: [],
    WonderfulPictures: [],
    MediaVideo: [],
    Meeting: [],
    DrawRecord: [],
    SingleMeeting: [],
    News: [],
    MeetingDetail: [],
    NewsDetail: [],
    SingleNews: [],
    Activity: [],
    SingleActivity: [],
}